# Generated by Django 4.2.29 on 2026-05-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="-", max_length=20),
            preserve_default=False,
        ),
    ]
