# Generated by Django 4.2.30 on 2026-05-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_user_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
