# Generated by Django 4.2.29 on 2026-05-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0003_rename_create_at_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
