# Generated by Django 4.2.29 on 2026-05-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slugfield",
            field=models.SlugField(default="-", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post/"),
        ),
    ]
