# Generated by Django 4.2.29 on 2026-05-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0005_post_slugfield_alter_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="slugfield",
            new_name="slug",
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
