# Generated by Django 4.2.29 on 2026-05-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0006_rename_slugfield_post_slug_alter_post_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
