# Generated by Django 4.2.29 on 2026-06-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0008_alter_comment_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
    ]
